### ISSUE TITLE
webrtc-sys build for linux?

### ISSUE THREAD

**Issue by singpolyma** [livekit/client-sdk-rust#82]
It seems that build.rs fails on linux right now

**Comment by theomonnom** [comment]
Hey, the SDK should build properly on Linux, can you send me your build logs?

**Comment by singpolyma** [comment]
Sorry about this one, I think I was confused by a different error I was getting.

**Comment by singpolyma** [comment]
(which is to say the actual build failure is https://github.com/webrtc-sdk/webrtc-build/issues/16 )

**Comment by theomonnom** [comment]
We're not using this repo for our builds.
For linux, I'm using this [script](https://github.com/livekit/client-sdk-rust/blob/main/webrtc-sys/libwebrtc/build_linux.sh)

**Comment by singpolyma** [comment]
Oh, I see that https://github.com/livekit/client-sdk-rust/blob/main/webrtc-sys/build.rs no longer points over there and that the last upload to crates.io was 5 months ago.  I will figure out how to ask cargo to pull from git as obviously it's not helpful for me to be trying old things and reporting on it. Sorry about the noise.
