### ISSUE TITLE
Feature to build livekit crate without webrtc?

### ISSUE THREAD

**Issue by singpolyma** [livekit/client-sdk-rust#83]
For my purposes I mostly want the `signal_client` and such, but don't need the livekit-webrtc related features to actually do the ICE etc, so it would be nice to be able to depend on the library and disable a feature or similar to not need those dependencies.

**Comment by davidzhao** [comment]
Closing as this is currently not planned. our priorities are to get this SDK to be production-viable asap. Introducing additional build variants will introduce additional complexities that we don't want right now.

**Comment by theomonnom** [comment]
Hey, the signal_client has been moved to the `livekit-api` crate :)
